
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

 
import { useRouter } from 'next/navigation'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const noNavbarPaths = ['/login', '/signup','/postProjects'];
  const shouldHideNavbar = router.pathname === '/postProjects';
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>

      <body className={inter.className}>
      {shouldHideNavbar && <Navbar />}
        {children}
        </body>
    </html>
  );
}
