import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "GvAutomata",
  description: "Automator for GitHub and Vercel",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 8d84249 (latest login page)
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </head>
      
=======
>>>>>>> 8d84249 (latest login page)
      <body className={inter.className}>{children}</body>
    </html>
  );
}
